apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: server-vpa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: server
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
    - containerName: "vpa10"
      controlledValues: "RequestsAndLimits"
      minAllowed:
        cpu: "250m"
      maxAllowed:
        cpu: "4"
    - containerName: "vpa15"
      controlledValues: "RequestsAndLimits"
      minAllowed:
        cpu: "250m"
      maxAllowed:
        cpu: "4"
    - containerName: "vpa20"
      controlledValues: "RequestsAndLimits"
      minAllowed:
        cpu: "250m"
      maxAllowed:
        cpu: "4"